### ISSUE TITLE
unintentional piece placing problem

### ISSUE THREAD

**Issue by FinJG** [TollyH/Shogi#2]
I have run into an issue where, if a player has selected a piece in hand and then decides to click a different piece in hand, it sometimes acts as if the player has clicked on the square above the piece they we're trying to select.

For example, in this position:
![image](https://user-images.githubusercontent.com/90899751/227662095-5e821881-9235-415e-8953-3076944b54d5.png)

if the player were to click on the rook in their hand, it would sometimes place the bishop on the ４五 square instead. :)

**Comment by TollyH** [comment]
SFEN reference: 3gk/2s1p/P4/1G3/K1S1R b RBb
